---
abstract: 'Parse CIGAR strings and translate coordinates to/from reference/query'
author:
  - 'Thomas Sibley <trsibley@uw.edu>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Cigar
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp: 0
  List::Util: 0
  Moo: 0
  Types::Standard: 1.000005
  namespace::clean: 0
  perl: 5.014
resources:
  bugtracker: https://github.com/MullinsLab/Bio-Cigar/issues
  homepage: https://github.com/MullinsLab/Bio-Cigar
  repository: https://github.com/MullinsLab/Bio-Cigar.git
version: 1.01
